- name: Determine session and run script
  env:
    FMP_API_KEY: ${{ secrets.FMP_API_KEY }}
    TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
    TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
  run: |
    # Get current UTC hour and minute
    hour=$(date -u +"%H")
    minute=$(date -u +"%M")
    total_minutes=$(( 10#$hour * 60 + 10#$minute ))

    # Block anything outside of 11:45 to 23:30 UTC
    allowed_start=$((11 * 60 + 45))   # 11:45 UTC = 705
    allowed_end=$((23 * 60 + 30))     # 23:30 UTC = 1410

    if [ "$total_minutes" -lt "$allowed_start" ] || [ "$total_minutes" -gt "$allowed_end" ]; then
      echo "Outside 11:45–23:30 UTC. Skipping run."
      exit 0
    fi

    # Define session boundaries in minutes since midnight UTC
    premarket_start=$((11 * 60 + 45))   # 11:45 UTC
    premarket_end=$((13 * 60 + 29))     # 13:29 UTC
    open_start=$((13 * 60 + 30))        # 13:30 UTC
    open_end=$((20 * 60 + 59))          # 20:59 UTC
    afterhours_start=$((21 * 60))       # 21:00 UTC
    afterhours_end=$((23 * 60 + 30))    # 23:30 UTC

    if [ "$total_minutes" -ge "$premarket_start" ] && [ "$total_minutes" -le "$premarket_end" ]; then
      arg="premarket"
    elif [ "$total_minutes" -ge "$open_start" ] && [ "$total_minutes" -le "$open_end" ]; then
      arg="open"
    elif [ "$total_minutes" -ge "$afterhours_start" ] && [ "$total_minutes" -le "$afterhours_end" ]; then
      arg="afterhours"
    else
      echo "Not in a valid session window for script execution."
      exit 0
    fi

    echo "Running: node lib/fmpTopGainers.js $arg"
    node lib/fmpTopGainers.js $arg